"""Windows agent: generates a PowerShell diagnostic script to run on the host.

wazuh-doctor runs on Linux and cannot execute commands on a Windows agent.
Instead of pretending to check one, this module emits a ready-to-run
PowerShell script covering the checks that actually matter there, which
the operator copies to the Windows host.
"""

from __future__ import annotations

from typing import List

from .base import Context, Module
from wdlib.common import Finding, Severity

AGENT_DIR = r"C:\Program Files (x86)\ossec-agent"

POWERSHELL_SCRIPT = r"""<#
    wazuh-agent-diagnose.ps1
    Generated by wazuh-doctor. Read-only: changes nothing.
    Run in an ELEVATED PowerShell on the Windows agent host.
#>

$ErrorActionPreference = 'Continue'
$agentDir = 'C:\Program Files (x86)\ossec-agent'
$logPath  = Join-Path $agentDir 'ossec.log'
$confPath = Join-Path $agentDir 'ossec.conf'

function Section($t) { Write-Host "`n=== $t ===" -ForegroundColor Cyan }

Section 'Service'
$svc = Get-Service -Name WazuhSvc -ErrorAction SilentlyContinue
if ($null -eq $svc) {
    Write-Host 'WazuhSvc NOT FOUND - the agent is not installed' -ForegroundColor Red
} else {
    $svc | Format-List Name, DisplayName, Status, StartType
    if ($svc.Status -ne 'Running') {
        Write-Host 'WazuhSvc is NOT running' -ForegroundColor Red
        Write-Host 'Fix:  Start-Service WazuhSvc'
    }
}

Section 'Version'
Get-Item (Join-Path $agentDir 'wazuh-agent.exe') -ErrorAction SilentlyContinue |
    Select-Object -ExpandProperty VersionInfo |
    Format-List FileVersion, ProductVersion

Section 'Manager address from ossec.conf'
if (Test-Path $confPath) {
    [xml]$conf = Get-Content $confPath
    $server = $conf.ossec_config.client.server
    $addr = $server.address; if (-not $addr) { $addr = $server.hostname }
    if (-not $addr) { $addr = $server.ip }
    Write-Host "Configured manager: $addr"
} else {
    Write-Host "ossec.conf not found at $confPath" -ForegroundColor Red
}

Section 'Manager reachability (1514 / 1515)'
if ($addr) {
    foreach ($p in 1514, 1515) {
        $r = Test-NetConnection -ComputerName $addr -Port $p -WarningAction SilentlyContinue
        $state = if ($r.TcpTestSucceeded) { 'OK' } else { 'FAILED' }
        $colour = if ($r.TcpTestSucceeded) { 'Green' } else { 'Red' }
        Write-Host ("  {0}:{1} -> {2}" -f $addr, $p, $state) -ForegroundColor $colour
    }
    Write-Host "  Ping: $((Test-Connection -ComputerName $addr -Count 2 -Quiet))"
} else {
    Write-Host '  skipped: no manager address parsed' -ForegroundColor Yellow
}

Section 'Recent agent log errors'
if (Test-Path $logPath) {
    Write-Host "-- last 15 lines --"
    Get-Content $logPath -Tail 15

    Write-Host "`n-- error/critical lines (last 40) --"
    Select-String -Path $logPath -Pattern 'ERROR|CRITICAL|Unable to connect|Connection refused|Unable to resolve' |
        Select-Object -Last 40 |
        ForEach-Object { $_.Line }
} else {
    Write-Host "ossec.log not found at $logPath" -ForegroundColor Red
}

Section 'Agent key file'
$keyPath = Join-Path $agentDir 'client.keys'
if (Test-Path $keyPath) {
    $lines = (Get-Content $keyPath | Where-Object { $_.Trim() -ne '' }).Count
    Write-Host "client.keys present with $lines entr(y|ies)"
} else {
    Write-Host 'client.keys MISSING - the agent is not enrolled' -ForegroundColor Red
    Write-Host 'Fix:  & "$agentDir\agent-auth.exe" -m <manager-ip>'
}

Section 'Done'
Write-Host 'Read-only diagnostic complete. No changes were made.'
"""


class WindowsAgentModule(Module):
    name = "windows_agent"
    title = "Windows agent (script generator)"
    description = "generates a PowerShell diagnostic script for Windows agent hosts"
    # Always applicable: a Linux manager commonly supervises Windows agents.
    requires = ()

    def run(self, ctx: Context) -> List[Finding]:
        return [
            self.finding(
                Severity.INFO,
                "PowerShell diagnostic script for Windows agents",
                "wazuh-doctor runs on Linux and cannot inspect a Windows agent "
                "remotely, so it generates a read-only PowerShell script instead; "
                "run it in an elevated PowerShell on each Windows agent host",
                evidence=(
                    POWERSHELL_SCRIPT
                    + "\n\nSave as wazuh-agent-diagnose.ps1 and run:\n"
                    + r"    powershell -ExecutionPolicy Bypass -File .\wazuh-agent-diagnose.ps1"
                ),
                fix=(
                    "Copy the script above to the Windows host, then run it in an "
                    "elevated PowerShell. It reports service state, agent version, "
                    "configured manager address, TCP reachability of 1514/1515, "
                    "recent log errors and enrollment state."
                ),
                verify=r"powershell -ExecutionPolicy Bypass -File .\wazuh-agent-diagnose.ps1",
            )
        ]
